[package]
name = "unilink-async-rs"
version = "0.1.0"
authors = ["lle-bout"]
edition = "2018"

[dependencies]
tokio = {version = "0.1.18", features = ["async-await-preview"]}
ed25519-dalek = "1.0.0-pre.1"
tk-listen = "0.2"
miniserde = "0.1"
futures = "0.1"